#!/usr/bin/env php

<?php
require __DIR__ . '/vendor/autoload.php';

use Commands\AppKey;
use Commands\ClearLog;
use Commands\JWTSecret;
use Commands\ModelCommand;
use Commands\ServeCommand;
use Commands\MigrateCommand;
use Commands\MigrationCommand;
use Commands\ControllerCommand;
use Symfony\Component\Console\Application;

$application = new Application();

# add our commands
$application->add(new ServeCommand());
$application->add(new ControllerCommand());
$application->add(new MigrationCommand());
$application->add(new MigrateCommand());
$application->add(new ModelCommand());
$application->add(new JWTSecret());
$application->add(new ClearLog());
$application->add(new AppKey());

$application->run();
